### ISSUE TITLE
implement tfgrid actions

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/crystalhandler#2]
possible implementations

- https://github.com/rogchap/v8go modify the existing javascript (typescript) client to be compatible with our messages 
- run the same code but then in rust based javascript runner (much more packaged): denon
- re-implement in golang (our favorite, will be better and more clean)

use websockets & resp

**Comment by xmonader** [comment]
https://github.com/threefoldtech/home/issues/1281 cross reference
