### ISSUE TITLE
can't use example for twin actions

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/crystalhandler#7]
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/6021844/185729854-8bc4a1eb-4cba-4bee-b437-359cafe1c6b5.png">

used crystallib/twinclient2/examples/vm_deploy1.v

which came from readme README.md

**Comment by despiegk** [comment]
its not clear to me how to start the websocket server, does this have to be in same process as the example script?
please help me improve the script then so it starts the webserver & launches the example

**Comment by xmonader** [comment]
https://github.com/freeflowuniverse/twinactions/tree/development/pocTS/server only need to run flow1server.v or flow2server.v
